### ISSUE TITLE
Check if the @ can be required when talking to the bot

### ISSUE THREAD

**Issue by KeesCBakker** [KeesCBakker/hubot-command-mapper#3]
^@hubot reacts, but ^hubot  as well.

**Comment by lizhi1989** [comment]
i have similar issue where we require to talk to bot using bot's alias but it response with invalid syntax.

**Comment by KeesCBakker** [comment]
So the bot does react to it's name, but not to the alias?

**Comment by lizhi1989** [comment]
> So the bot does react to it's name, but not to the alias?

Ya, I had one bot using hubot-rocketchat-boilerplate with following name and alias.
export HUBOT_NAME=kelvinbot
export HUBOT_ALIAS=john

it react to "kelvinbot count from 10 to 15".
but not "john count from 10 to 15"
It reply with "Invalid syntax"

**Comment by KeesCBakker** [comment]
I've looked into the problem and saw that the name and alias were not mapped equally. I added the alias to the regular expression matching as well. I've updated to package to version 2.0.3. Can you verify if these changes work for you?

**Comment by lizhi1989** [comment]
> I've looked into the problem and saw that the name and alias were not mapped equally. I added the alias to the regular expression matching as well. I've updated to package to version 2.0.3. Can you verify if these changes work for you?

Thanks it works now.
Just that one of your example in github is broken.
the match index is now 4 & 5.
`
const { mapper } = require("hubot-command-mapper");
module.exports = robot => {
  const tool = {
    name: "count",
    commands: [{
        name: "from",
        capture: "(\\d+) to (\\d+)",
        execute: context => {
          const a = Number(context.match[3])
          const b = Number(context.match[4])

          for (let i = a; i < b + 1; i++) {
            context.res.reply(`${i}!`)
          }
        }
    }]
  };

  mapper(robot, tool);
};`

**Comment by KeesCBakker** [comment]
Cool... I'll look into it. It really shows how fragile regex parsing is (that's why I included the named regex package).

**Comment by KeesCBakker** [comment]
Added the change to the readme. Published a new version.
